name: core
description: "A new Flutter package project."
version: 0.0.1

resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  google_fonts: ^6.3.3
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  nested: ^1.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.0.0
  json_serializable: ^6.11.0
  build_runner: ^2.4.15
