name: app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  core:
  shared:
  premium:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.11.0
  go_router_builder: ^4.1.3

flutter:
  uses-material-design: true

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree/static/Figtree-Regular.ttf
        - asset: assets/fonts/Figtree/static/Figtree-Italic.ttf
          style: italic
        - asset: assets/fonts/Figtree/static/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/Figtree/static/Figtree-Medium.ttf
          weight: 500
        - asset: assets/fonts/Figtree/static/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Figtree/static/Figtree-Light.ttf
          weight: 300
        - asset: assets/fonts/Figtree/static/Figtree-Black.ttf
          weight: 900
  assets:
    - assets/images/crown.webp
    - assets/images/gold.webp
    - assets/images/insurance.webp
    - assets/images/bills.webp
    - assets/images/electricity.webp
    - assets/images/person.webp
